version: '3.7'

services:
    web:
        build: .
        command: bash -c "gunicorn elawyer/elawyer.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/usr/src/elawyer-backend
        expose:
            - 8000
        env_file:
            - ./.env
            
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    postgres_data:
