version: '3.7'

services:
    web:
        build: .
        command: bash -c "gunicorn elawyer/elawyer.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/usr/src/elawyer-backend
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=dev_user
            - POSTGRES_PASSWORD=dev_password
            - POSTGRES_DB=elawyer_dev
          
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    postgres_data:
