version: '3.7'

services:
    web:
        build: ./elawyer-app/elawyer-backend
        command: cd /elawyer-backend
        command: gunicorn elawyer_dev.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/elawyer-app/
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=dev_user
          - POSTGRES_PASSWORD=dev_password
          - POSTGRES_DB=elawyer_dev

    volumes:
        postgres_data:

    nginx:
        build: ./elawyer-app/elawyer-backend/nginx
        ports:
            - 80:80
        depends_on:
            - web