# Generated by Django 2.2.20 on 2021-07-11 22:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('country', django_countries.fields.CountryField(blank=True, default='NG', max_length=2, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Region')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Town')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('service_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('real_estate', 'Real Etstate'), ('civil case', 'Civil Case'), ('litigation', 'Litigation'), ('human right', 'Human Right'), ('employment agreement', 'Employment Agreement'), ('business agreement', 'Business Agreement')], max_length=255), blank=True, size=None, verbose_name='Service Interest')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('level_of_education', models.CharField(choices=[('phd', 'Doctor of Philosophy (Phd.)'), ('msc', 'Master of Science (MSc.)'), ('ma', 'Master of Art (MA)'), ('mit', 'Master of Infomation Technology (MIT)'), ('pgd', 'Post Graduate Diploma (PGD)'), ('mbbs', 'Bachelor of Medcine & Surgery (MBBS, BMBS'), ('bsc', 'Bachelor of Science (BSc)'), ('ba', 'Bachelor of Art (BA)'), ('hnd', 'Higher National Diploma (HND)'), ('nd', 'National Diploma (ND)'), ('high school', 'High School'), ('basic', 'Basic/Elementary School'), ('non', 'No Formal Education'), ('', 'Would rather not specify')], max_length=10, verbose_name='Highest Level of Education')),
                ('heard_about_us', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('friend', 'Friend'), ('family', 'Family'), ('elawyerng staff', 'Elawyer-Ng Staff'), ('referral', 'Referral'), ('other', 'Other')], default='', max_length=100, null=True, verbose_name='How user heard about us')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Is email verified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name': 'historical account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('country', django_countries.fields.CountryField(blank=True, default='NG', max_length=2, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Region')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Town')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('service_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('real_estate', 'Real Etstate'), ('civil case', 'Civil Case'), ('litigation', 'Litigation'), ('human right', 'Human Right'), ('employment agreement', 'Employment Agreement'), ('business agreement', 'Business Agreement')], max_length=255), blank=True, size=None, verbose_name='Service Interest')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('level_of_education', models.CharField(choices=[('phd', 'Doctor of Philosophy (Phd.)'), ('msc', 'Master of Science (MSc.)'), ('ma', 'Master of Art (MA)'), ('mit', 'Master of Infomation Technology (MIT)'), ('pgd', 'Post Graduate Diploma (PGD)'), ('mbbs', 'Bachelor of Medcine & Surgery (MBBS, BMBS'), ('bsc', 'Bachelor of Science (BSc)'), ('ba', 'Bachelor of Art (BA)'), ('hnd', 'Higher National Diploma (HND)'), ('nd', 'National Diploma (ND)'), ('high school', 'High School'), ('basic', 'Basic/Elementary School'), ('non', 'No Formal Education'), ('', 'Would rather not specify')], max_length=10, verbose_name='Highest Level of Education')),
                ('heard_about_us', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('friend', 'Friend'), ('family', 'Family'), ('elawyerng staff', 'Elawyer-Ng Staff'), ('referral', 'Referral'), ('other', 'Other')], default='', max_length=100, null=True, verbose_name='How user heard about us')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Is email verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
        ),
    ]
